* This .do file conducts simulations for the Cambodian graph
* It is (5/6) of the .do files in this project. 
* .do file author: Matt Collin (mcollin@worldbank.org) 
* This version: October 22, 2019
* Changes (07-26-18): calculations for GDP per capita, including changes to poverty calculations

* Paths are set in master.do — run master.do first to define globals
* Required globals: $root, $input, $output, $graphs, $do

* Installing customs modules (commented out unless needed)
*ssc install mmerge	

* Setting the parameters for the model
scalar alpha    = 1/3						// Cobb-Douglas factor share for capital 
scalar pgr      = .013					    // This is the growth rate of productivity
scalar delta    = .05						// Depreciation rate of capital 
scalar phi      = 0.08						// Mincerian return to education
scalar endyear  = 2100						// Last year we want the simulation to run to 
scalar ys_max   = 12						// Set max for years of schooling
scalar adys_max = 12						// Set max for quality adjusted years of schooling


*****************************************************************



* We start with the results of the simulation exercise
* Loading Projections file
use "$output/hc_projections.dta", clear								



* Creating frame
use "$output\human_capital_2015.dta", clear
keep wbcode age_bin
local  ts = (endyear - 2015)/5 + 1
expand `ts'
bys wbcode age_bin: gen year = (2010 + 5*_n) 

* Keep working age population
keep if age_bin >=20 & age_bin <=60

* Merge in population bin data
mmerge wbcode year age_bin  using "$output/population_bins.dta", type(1:1) unmatched(master) umatch(iso3c year age_bin)

* Merging in starting values of capital, human capital, GDP
mmerge wbcode year age_bin using "$output\human_capital_2015.dta", type(1:1) unmatched(master) umatch(wbcode year age_bin)

* Loading in values generated by NPV calculation file
mmerge wbcode using "$output/gcf_pv.dta", type(n:1) unmatched(master) ukeep(gcf_initial-gcf_sc5)

* We will only use the population level data for now, so drop female and male-specific estimates
drop *FEMALE *MALE

* Calculating age-bin aggregate human capital at T0
gen a_hc = pop_BOTH * hc_BOTH													// Which is the total pop for the age bin X the average HC for that age bin								

keep if wbcode == "KHM" 

*****************************************
* STEP 1: Age-bin specific calculations *
*****************************************

* CONSTANT SCENARIO: HC per worker improves due to aging out of older cohorts  *

gen ys_BOTH_constant   = ys_BOTH
gen qual_BOTH_constant = qual_BOTH
gen hch_BOTH_constant  = hch_BOTH 

* We're doing this in a less complicated way than the previous version: we're just using the [_n] function to grab earlier values. 
* Note that these will need to be adjusted if we decide upon a differnet number of age-bins
sort wbcode year age_bin 
forvalues t = 2020(5)2100 {																			     // Cycling over subsequent years
		bys wbcode: replace ys_BOTH_constant = ys_BOTH_constant[_n-9] if age_bin == 20  & year == `t'    // Each new 20-24 cohort takes on the educational attainment of the previous 20-24 cohort (
		bys wbcode: replace ys_BOTH_constant = ys_BOTH_constant[_n-10] if age_bin >  20 & year == `t'    // Every other cohort moves `forward' in time, carrying forward its education attainment
		
		bys wbcode: replace hch_BOTH_constant  = hch_BOTH_constant[_n-9]  if year == `t' 				 // Human Capital from health remains constant
		bys wbcode: replace qual_BOTH_constant = qual_BOTH_constant[_n-9] if year == `t' 				 // Education quality remains constant
}
	
gen adye_BOTH_constant = ys_BOTH_constant * qual_BOTH_constant					// Generating new adjusted years of schooling
gen hce_BOTH_constant  = exp(phi*(min(adye_BOTH_constant,adys_max)-adys_max))		 		// Generating new human capital from education (note we are capping adjusted years of schooling at 12)
gen hc_BOTH_constant   = hch_BOTH_constant * hce_BOTH_constant 				    // Generating new human capital under constant scenario
gen a_hc_constant      = pop_BOTH * hc_BOTH_constant		

				
								
* *	* SCENARIO 1: HCI changes by 4.8% over the first five years, then stays fixed at that value, investment rate remains the same
preserve
do "$do/2.1 (background) scenario.do" 													// Re-calculating the `typical' scenario
restore
gen hc_BOTH_hci6 = hc_BOTH														// Setting initial (t0) value
sort wbcode year age_bin 
forvalues t = 2020(5)2100 {
		bys wbcode: replace hc_BOTH_hci6 = 1-((1-hci_gap_5rate_50)*(1-hc_BOTH[1])) if age_bin == 20 & year == `t'   // The newest cohort closes 5% of the gap 
		bys wbcode: replace hc_BOTH_hci6 = hc_BOTH_hci6[_n-10]            		  if age_bin >  20 & year == `t'   // Every other cohort moves `forward' in time, carrying forward its education attainment
}
gen a_hc_hci6      = pop_BOTH * hc_BOTH_hci6


* *	* SCENARIO 2: The investment rate immediately moves to the same steady state as Scenario 1, while HCI remains constant
sort wbcode year age_bin 
scalar hcchange = hc_BOTH_hci6[10] / hc_BOTH_hci6[1]
scalar hcpincrease = ((hc_BOTH_hci6[10]- hc_BOTH_hci6[1])/ hc_BOTH_hci6[1])* 100
scalar hc_start = hc_BOTH_hci6[1]
scalar hc_end   = hc_BOTH_hci6[10]

gen     gcf_constant     = gcf[1]
gen     gcf_hci6 	 	 = gcf[1]
gen     gcf_investment   = gcf[1]
replace gcf_investment	 = gcf[1]* (hcchange) ^ ((1-alpha)/alpha)
local   gcf_i			 = round((gcf_investment[1] - gcf[1])*100,.1)				// Saving for later
scalar  gcf_o            = gcf[1]*100
scalar  gcf_i            = gcf_investment[1]*100


scalar factorscale = (hcchange) ^ ((1-alpha)/alpha)								// Saving for later
gen ys_BOTH_investment   = ys_BOTH
gen qual_BOTH_investment = qual_BOTH
gen hch_BOTH_investment  = hch_BOTH 

* We're doing this in a less complicated way than the previous version: we're just using the [_n] function to grab earlier values. 
* Note that these will need to be adjusted if we decide upon a differnet number of age-bins
sort wbcode year age_bin 
forvalues t = 2020(5)2100 {																			     // Cycling over subsequent years
		bys wbcode: replace ys_BOTH_investment = ys_BOTH_investment[_n-9] if age_bin == 20  & year == `t'    // Each new 20-24 cohort takes on the educational attainment of the previous 20-24 cohort (
		bys wbcode: replace ys_BOTH_investment = ys_BOTH_investment[_n-10] if age_bin >  20 & year == `t'    // Every other cohort moves `forward' in time, carrying forward its education attainment
		
		bys wbcode: replace hch_BOTH_investment  = hch_BOTH_investment[_n-9]  if year == `t' 				 // Human Capital from health remains constant
		bys wbcode: replace qual_BOTH_investment = qual_BOTH_investment[_n-9] if year == `t' 				 // Education quality remains constant
}
	
gen adye_BOTH_investment = ys_BOTH_investment * qual_BOTH_investment				// Generating new adjusted years of schooling
gen hce_BOTH_investment  = exp(phi*(min(adye_BOTH_investment,adys_max)-adys_max))	// Generating new human capital from education (note we are capping adjusted years of schooling at 12)
gen hc_BOTH_investment   = hch_BOTH_investment * hce_BOTH_investment 				// Generating new human capital under constant scenario
gen a_hc_investment      = pop_BOTH * hc_BOTH_investment							// Generating total human capital per age bin under constant scenario							


* *	* SCENARIO 3: The investment rate immediately moves to the NPV equivalent of scenario 1
gen gcf_npv = gcf[1]
replace gcf_npv = gcf_sc4
local   gcf_npv			 = round((gcf_npv[1] - gcf[1])*100,.1)						// Saving for later


gen ys_BOTH_npv   = ys_BOTH
gen qual_BOTH_npv = qual_BOTH
gen hch_BOTH_npv  = hch_BOTH 

* We're doing this in a less complicated way than the previous version: we're just using the [_n] function to grab earlier values. 
* Note that these will need to be adjusted if we decide upon a differnet number of age-bins
sort wbcode year age_bin 
forvalues t = 2020(5)2100 {																			     // Cycling over subsequent years
		bys wbcode: replace ys_BOTH_npv = ys_BOTH_npv[_n-9] if age_bin == 20  & year == `t'    // Each new 20-24 cohort takes on the educational attainment of the previous 20-24 cohort (
		bys wbcode: replace ys_BOTH_npv = ys_BOTH_npv[_n-10] if age_bin >  20 & year == `t'    // Every other cohort moves `forward' in time, carrying forward its education attainment
		
		bys wbcode: replace hch_BOTH_npv  = hch_BOTH_npv[_n-9]  if year == `t' 				 // Human Capital from health remains constant
		bys wbcode: replace qual_BOTH_npv = qual_BOTH_npv[_n-9] if year == `t' 				 // Education quality remains constant
}
	
gen adye_BOTH_npv = ys_BOTH_npv * qual_BOTH_npv							// Generating new adjusted years of schooling
gen hce_BOTH_npv  = exp(phi*(min(adye_BOTH_npv,adys_max)-adys_max))		// Generating new human capital from education (note we are capping adjusted years of schooling at 12)
gen hc_BOTH_npv   = hch_BOTH_npv * hce_BOTH_npv 				    	// Generating new human capital under constant scenario
gen a_hc_npv      = pop_BOTH * hc_BOTH_npv				


*****************************************************************************
* STEP 2: Collapsing to country-year level and making final HC calculations *
*****************************************************************************

* Summing up total human capital
collapse (sum) pop_BOTH a_hc* (first) wbcountryname ck gcf* gini pov* gdp Incomegroup Lendingcategory Region, by(wbcode year)	// This gives us total working population for each country year and total HC for that country year

gen hcpw_constant = a_hc_constant / pop_BOTH
gen hcpw_investment = a_hc_investment / pop_BOTH
gen hcpw_hci6     = a_hc_hci6 	  / pop_BOTH
gen hcpw_npv     = a_hc_npv 	  / pop_BOTH


* Bringing in total population numbers 
mmerge wbcode year using "$output/total_population.dta", umatch(iso3c year) type(1:1) unmatched(master)


*******************************************
* STEP 3: Calculating productivity growth *
*******************************************
*Generating year 0 productivity 
gen gdppw = gdp  / pop_BOTH											if year == 2015	 // GDP per worker
gen hcpw  = a_hc / pop_BOTH											if year == 2015	 // HC  per worker
gen kpw   = ck   / pop_BOTH											if year == 2015	 // K   per worker 
gen a     = gdppw / ( ((kpw)^(alpha))*((hcpw_constant)^(1-alpha)))	if year == 2015	 // Year 0 productivity

* Now rolling the model forward and calculating productivity growth
sort wbcode year
forvalues t = 2020(5)2100 {
	bys  wbcode: replace a = a[1]*(1+pgr)^((`t'-2015))	if year ==`t'		    // Calculating productivity growth
}


**********************
* Final Calculations * 
**********************

* Each country has a Gini coefficient value taken at t0 (2015). We use that value to calculate the 
* variance of the log distribution of income: 
gen sigma = invnormal( ( gini + 1 )/2 ) * sqrt(2) 
bys wbcode: replace sigma = sigma[1] if year > 2015								// We assume that the variance remains fixed

* Final GDP and poverty calculations
foreach scenario in constant investment hci6 npv {								// Calculating capital stock and GDP for each scenario
	sort wbcode year 
	gen  ck_`scenario'  = ck
	gen  kpw_`scenario' = ck_`scenario' / pop_BOTH								// Calculating capital per worker in the first period
	gen  pov_`scenario' = pov													// Poverty rate
	gen  pov320_`scenario' = pov320												// Poverty rate
	gen  pov550_`scenario' = pov550												// Poverty rate

	* Rolling forward in five year intervals and using the secnario specific values of capital and human capital
	forvalues t = 2020(5)2100 {
		bys wbcode: replace kpw_`scenario' = 	(pop_BOTH[_n-1]/pop_BOTH)*( kpw_`scenario'[_n-1] + 5 * (gcf_`scenario'[_n-1] * a[_n-1] * (kpw_`scenario'[_n-1]^(alpha))*(hcpw_`scenario'[_n-1]^(1-alpha)) - delta * kpw_`scenario'[_n-1]) ) if year == `t'
	}

	* Generating GDP per worker
	gen     gdppw_`scenario' = a * (kpw_`scenario'^(alpha))*(hcpw_`scenario'^(1-alpha))
	
	
	* Calculating GDP per capita
	gen    gdppc_`scenario' =  gdppw_`scenario' * (total_working/total_pop)		// GDP per capita is defined as GDP per worker X the working age fraction 
	
	* Generating poverty rate and poverty rate relative to baseline
	foreach p in pov pov320 pov550 {
		bys wbcode: replace `p'_`scenario'   = normal(invnormal(`p'[1]) - (1/sigma)* ln((gdppc_`scenario')/(gdppc_`scenario'[1]))) if year > 2015  // Note that [1] indicates the value in year 0 for that country
					gen     `p'_`scenario'_r = `p'_`scenario' / `p'_constant
					gen     `p'_`scenario'_p = `p'_`scenario' - `p'_constant
	}
	
	* Calculating relative GDP
	gen     gdppw_`scenario'_r = gdppw_`scenario' / gdppw_constant			// Calculating GDP relative to baseline	
	gen     gdppc_`scenario'_r = gdppc_`scenario' / gdppc_constant			// Calculating GDP relative to baseline	
	
	
	lab var ck_`scenario'      "Capital stock (`scenario' scenario)"
	lab var kpw_`scenario'     "Capital per worker (`scenario' scenario)" 
	lab var gdppw_`scenario'   "GDP per worker (`scenario' scenario)" 
	lab var gdppc_`scenario'   "GDP per capita (`scenario' scenario)"
	lab var gdppw_`scenario'_r "GDP per worker (`scenario' scenario) relative to baseline"
	lab var gdppc_`scenario'_r "GDP per capita (`scenario' scenario) relative to baseline"
	lab var pov_`scenario'     "Poverty rate (`scenario' scenario)"
	lab var pov_`scenario'_r   "Poverty rate (`scenario' scen1ario) relative to baseline"
	lab var pov_`scenario'_p   "Poverty rate percentage point difference (`scenario' scenario) from baseline"
	
}


	scalar lrate50 = round(hci_gap_5rate_50p,.1)
	scalar lrate75 = round(hci_gap_5rate_75p,.1)
	local  lrate50 = lrate50
	local  lrate75 = lrate75 

twoway (line gdppc_hci6_r year, sort lcolor(black) lwidth(thick)) 				///
	   (line gdppc_investment_r year, sort lcolor(black) lwidth(thick) lpattern(vshortdash))			///
	   (line gdppc_npv_r year, sort lcolor(black) lwidth(thick) lpattern(dash))	///
	   , ytitle(GDP-per-capita relative to baseline scenario) xtitle(" ") 		///
	   legend(order(1 "Immediate reduction in HCI gap by `lrate50'%" 2 "Immediate increase in investmentby `gcf_i'  percentage points in 2015 (same steady state as reduction in HCI gap" 3 "Immediate increase in investmentby `gcf_npv'  percentage points in 2015 (same PV as reduction in HCI gap)") 			///
	   cols(1) region(lcolor(white))) xsize(5) ysize(3)   graphregion(fcolor(white) lcolor(white))

gr_edit .gmetric_mult = 0.8

	 
gr export "$graphs/cambodia.png", as(png) width(2500) replace
gr export "$graphs/cambodia.eps", as(eps)  replace
******************************
* Exporting results to LaTex *
******************************
* Scaling up fractions to %
scalar gdppcXXXhc  = (gdppc_hci6_r[4]-1)*100
scalar gdppcXXXinv = (gdppc_investment_r[4]-1)*100
scalar gdppcXXXnpv = (gdppc_npv_r[4]-1)*100
texresults using results_cambodia.tex, texmacro(hcstart)     result(hc_start)  replace round(.001) unitzero
texresults using results_cambodia.tex, texmacro(hcend)     result(hc_end)  append round(.001) unitzero
texresults using results_cambodia.tex, texmacro(hcpincrease)     result(hcpincrease)  append round(.1)
texresults using results_cambodia.tex, texmacro(hcchange)     result(hcchange)  append round(.0001)
texresults using results_cambodia.tex, texmacro(factorscale)     result(factorscale)  append round(.0001)
texresults using results_cambodia.tex, texmacro(gcfo)     result(gcf_o)  append round(.1)
texresults using results_cambodia.tex, texmacro(gcfi)     result(gcf_i)  append round(.1)
texresults using results_cambodia.tex, texmacro(gcfd)     result(`gcf_i')  append round(.1)
texresults using results_cambodia.tex, texmacro(gcfdn)     result(`gcf_npv')  append round(.1)
texresults using results_cambodia.tex, texmacro(gdppcXXXhc)     result(gdppcXXXhc)  append round(.1)
texresults using results_cambodia.tex, texmacro(gdppcXXXinv)     result(gdppcXXXinv)  append round(.1)
texresults using results_cambodia.tex, texmacro(gdppcXXXnpv)     result(gdppcXXXnpv)  append round(.1)
* Generating figures for Jama and article: breakdown 
 use "$output/gcf_pv.dta", clear

mmerge wbcode 	      using "$output/country_categories.dta"      , type(n:1) 						    unmatched(master)  // WB Country Categories

gen diff_sc4 = gcf_sc4 - gcf_initial
gen diff_sc5 = gcf_sc5 - gcf_initial

bys Incomegroup: sum diff_sc4
bys Incomegroup: sum diff_sc5

* Low income
sum diff_sc4 if Incomegroup == "Low income"
scalar LIdiffsc4 = `r(mean)' * 100 
sum diff_sc5 if Incomegroup == "Low income"
scalar LIdiffsc5 = `r(mean)' * 100 

* Lower middle 
sum diff_sc4 if Incomegroup == "Lower middle income"
scalar LMdiffsc4 = `r(mean)' * 100 
sum diff_sc5 if Incomegroup == "Lower middle income"
scalar LMdiffsc5 = `r(mean)' * 100 

* Upper middle 
sum diff_sc4 if Incomegroup == "Upper middle income"
scalar UMdiffsc4 = `r(mean)' * 100 
sum diff_sc5 if Incomegroup == "Upper middle income"
scalar UMdiffsc5 = `r(mean)' * 100



texresults using results_cambodia.tex, texmacro(LIdiffscinv)     result(LIdiffsc4)  append round(.1) 
texresults using results_cambodia.tex, texmacro(LIdiffscnpv)     result(LIdiffsc5)  append round(.1) 
texresults using results_cambodia.tex, texmacro(LMdiffscinv)     result(LMdiffsc4)  append round(.1) 
texresults using results_cambodia.tex, texmacro(LMdiffscnpv)     result(LMdiffsc5)  append round(.1) 
texresults using results_cambodia.tex, texmacro(UMdiffscinv)     result(UMdiffsc4)  append round(.1) 
texresults using results_cambodia.tex, texmacro(UMdiffscnpv)     result(UMdiffsc5)  append round(.1) 







exit



2
